--insert into sample(id, name) values (1,'YAMADA');
--insert into sample(id ,name) values (2,'SATO');
--insert into sample(id, name) values (3,'TANAKA');
--insert into sample(id ,name) values (4,'SUZUKI');
--
--insert into messages values (1,'hoge' );
--insert into messages values (2,'fuga');